[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F"]
ignore = [
    "E501", # Line too long
    "E701", # Multiple statements on one line (colon)
    "E702", # Multiple statements on one line (semicolon)
    "E722", # Bare except
    "E731", # Lambda assignment
    "F403", # from module import *
    "F405", # Name may be undefined from star import
    "F401", # Unused import
    "F841", # Unused local variable
]

[tool.bandit]
exclude_dirs = ["scripts/venv", "infra/ai/ai-env", "venv"]
tests = ["B101", "B104", "B110", "B307"] # On se concentre sur les risques r√©els
