services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      # L'IP publique de votre domicile
      - WG_HOST=91.160.12.99
      # Le hash du mot de passe (généré avec bcrypt, avec les $ échappés pour Docker)
      - PASSWORD_HASH=$$2a$$10$$VlMlYBKSxOWaQbv4dX37vuSuXYMbO0B2TnPblntjMgLfrM/pohrwu
      # Pour que tout le trafic passe par le VPN (Netflix, etc.)
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
    ports:
      - "11940:51820/udp"
      - "11941:51821/tcp"
    volumes:
      - ./config:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always
