- Media:
    - Sonarr:
        icon: sonarr.png
        href: http://172.23.0.12:8989
        description: TV Series Management
        widget:
          type: sonarr
          url: http://172.23.0.12:8989
          key: 7be8638a56a44228a807ea850c997a12

    - Radarr:
        icon: radarr.png
        href: http://172.23.0.8:7878
        description: Movie Management
        widget:
          type: radarr
          url: http://172.23.0.8:7878
          key: 65ea98c94c02492396e19b2a05785034

- Download:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://172.23.0.6:8090
        description: Torrent Downloader
        widget:
          type: qbittorrent
          url: http://172.23.0.6:8090
          username: admin
          password: YOUR_PASSWORD # Update this later

- System:
    - Portainer:
        icon: portainer.png
        href: https://192.168.1.237:9443
        description: Docker Container Management
