---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

hostValidation: false

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
